# Generated by Django 4.1.2 on 2022-11-09 09:53

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('creator', models.CharField(max_length=100)),
                ('release_date', models.DateTimeField(blank=True)),
                ('genre', models.CharField(choices=[('FPS', 'First Person Shooter'), ('SIM', 'Simulation'), ('CB', 'City Builder'), ('HG', 'Horror Game'), ('RPG', 'Role Playing Game'), ('RC', 'Racing Game')], max_length=3)),
                ('age_rating', models.CharField(choices=[('f00', 'from 0'), ('f06', 'from 6'), ('f12', 'from 12'), ('f16', 'from 16'), ('f18', 'from 18')], default='f00', max_length=3)),
                ('upload_date', models.DateTimeField(blank=True, default=datetime.datetime.today)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', related_query_name='user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Game',
                'verbose_name_plural': 'Games',
                'ordering': ['title', 'genre'],
                'get_latest_by': 'release_date',
            },
        ),
    ]
