# Generated by Django 4.1.2 on 2022-11-09 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='age_rating',
            field=models.CharField(choices=[('0+', 'from 0'), ('6+', 'from 6'), ('12+', 'from 12'), ('16+', 'from 16'), ('18+', 'from 18')], default='0+', max_length=3),
        ),
    ]
