# Generated by Django 4.1.2 on 2023-01-29 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='product_data_pdf',
            field=models.FileField(default='', upload_to='documents/games'),
        ),
    ]
