# Generated by Django 4.1.2 on 2023-01-29 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Games', '0002_game_product_data_pdf'),
        ('Games', '0002_review'),
    ]

    operations = [
    ]
