# Generated by Django 4.1.2 on 2022-11-09 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Games', '0002_alter_game_age_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='upload_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
