# Generated by Django 4.1.2 on 2023-01-29 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Games', '0004_comment_approved_comment_reported_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='reported',
        ),
        migrations.AlterField(
            model_name='comment',
            name='approved',
            field=models.BooleanField(default=True),
        ),
    ]
