# Generated by Django 4.1.2 on 2023-02-01 00:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Games', '0006_comment_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='total_rating',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
