# Generated by Django 4.1.2 on 2022-11-09 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Games', '0006_alter_game_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='genre',
            field=models.CharField(choices=[('FPS', 'First Person Shooter'), ('SIM', 'Simulation'), ('CB', 'City Builder'), ('HG', 'Horror Game'), ('RPG', 'Role Playing Game'), ('RC', 'Racing Game')], max_length=3),
        ),
    ]
