# Generated by Django 4.1.2 on 2023-02-01 00:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Games', '0007_game_total_rating_delete_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='total_rating',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
