# Generated by Django 4.1.2 on 2022-11-23 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Games', '0008_comment_vote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='game',
        ),
    ]
